// source: Message.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.InputMessage');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.MessageObject');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.InputMessage = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.InputMessage, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.InputMessage.displayName = 'proto.InputMessage';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.InputMessage.prototype.toObject = function(opt_includeInstance) {
  return proto.InputMessage.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.InputMessage} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.InputMessage.toObject = function(includeInstance, msg) {
  var f, obj = {
    ipaddress: jspb.Message.getFieldWithDefault(msg, 1, ""),
    messagetoinput: (f = msg.getMessagetoinput()) && proto.MessageObject.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.InputMessage}
 */
proto.InputMessage.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.InputMessage;
  return proto.InputMessage.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.InputMessage} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.InputMessage}
 */
proto.InputMessage.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setIpaddress(value);
      break;
    case 2:
      var value = new proto.MessageObject;
      reader.readMessage(value,proto.MessageObject.deserializeBinaryFromReader);
      msg.setMessagetoinput(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.InputMessage.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.InputMessage.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.InputMessage} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.InputMessage.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getIpaddress();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getMessagetoinput();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.MessageObject.serializeBinaryToWriter
    );
  }
};


/**
 * optional string ipAddress = 1;
 * @return {string}
 */
proto.InputMessage.prototype.getIpaddress = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.InputMessage} returns this
 */
proto.InputMessage.prototype.setIpaddress = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional MessageObject messageToInput = 2;
 * @return {?proto.MessageObject}
 */
proto.InputMessage.prototype.getMessagetoinput = function() {
  return /** @type{?proto.MessageObject} */ (
    jspb.Message.getWrapperField(this, proto.MessageObject, 2));
};


/**
 * @param {?proto.MessageObject|undefined} value
 * @return {!proto.InputMessage} returns this
*/
proto.InputMessage.prototype.setMessagetoinput = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.InputMessage} returns this
 */
proto.InputMessage.prototype.clearMessagetoinput = function() {
  return this.setMessagetoinput(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.InputMessage.prototype.hasMessagetoinput = function() {
  return jspb.Message.getField(this, 2) != null;
};


